@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam sequenceParticipant underline

actor User
participant "View Scores Button" as BU
participant "ViewScoresController" as A
participant "ViewScoresInputBoundary\n(Interactor)" as B
participant "ViewScoresDataAccessInterface" as C
participant "ViewScoresOutputData" as D
participant "ViewScoresOutputBoundary\n(Presenter)" as E
participant "ViewScoresViewModel" as F
participant "ViewScoresState" as G

User -> BU: presses
activate BU

BU -> A: execute()
activate A

A -> B: execute()
activate B

B -> C: getLastTenScores()
activate C

C --> B
deactivate C

B -> D: <creates>
activate D

D --> B
deactivate D

B -> E: prepareSuccessView(viewScoresOutputData)
activate E

E -> F: getState()
activate F

F --> E
deactivate F

E -> G: setViewScoresMessage(message)
activate G

G --> E
deactivate G


@enduml